<!doctype html>
<html lang="en-AU">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @php($workDescription = $work->description ?: 'A completed Brisbane tiling project by Ozghan.au.')
    <title>{{ $work->title }} | Brisbane Tiling | Ozghan.au</title>
    <meta name="description" content="{{ $workDescription }}">
    @include('site.partials.seo', ['seoTitle' => $work->title.' | Brisbane Tiling | Ozghan.au', 'seoDescription' => $workDescription, 'seoType' => 'article'])
    @php($workImage = $work->image_path ? (\Illuminate\Support\Str::startsWith($work->image_path, ['services/', 'works/']) ? url('/storage/'.ltrim($work->image_path, '/')) : (\Illuminate\Support\Str::startsWith($work->image_path, ['http://', 'https://']) ? $work->image_path : asset(ltrim($work->image_path, '/')))) : asset('logo.png'))
    <script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'CreativeWork', 'headline' => $work->title, 'name' => $work->title, 'description' => $workDescription, 'url' => url('/our-work/'.$work->slug), 'image' => $workImage, 'creator' => ['@id' => 'https://ozghan.au/#business'], 'spatialCoverage' => ['@type' => 'Place', 'name' => $work->location ?: 'Brisbane, Queensland'], 'about' => ['@type' => 'Service', 'name' => ($work->category ?: 'Tiling').' in Brisbane'], 'dateCreated' => $work->completed_at?->toDateString(), 'additionalProperty' => $work->area_m2 ? [['@type' => 'PropertyValue', 'name' => 'Tiled area', 'value' => (float) $work->area_m2, 'unitText' => 'square metres']] : []], JSON_UNESCAPED_SLASHES) !!}</script>
    <script type="application/ld+json">{!! json_encode(['@context' => 'https://schema.org', '@type' => 'BreadcrumbList', 'itemListElement' => [['@type' => 'ListItem', 'position' => 1, 'name' => 'Home', 'item' => url('/')], ['@type' => 'ListItem', 'position' => 2, 'name' => 'Our Work', 'item' => url('/our-work')], ['@type' => 'ListItem', 'position' => 3, 'name' => $work->title, 'item' => url('/our-work/'.$work->slug)]]], JSON_UNESCAPED_SLASHES) !!}</script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root{--bg:#f2efea;--ink:#23201c;--soft:#5b564f;--clay:#b8541f;--line:#d8d0c6;--display:'Manrope',Arial,sans-serif;--body:'Manrope',Arial,sans-serif}
        *{box-sizing:border-box}body{min-height:100vh;display:flex;flex-direction:column;margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 var(--body)}a{color:inherit;text-decoration:none}.container{max-width:1120px;margin:auto;padding:0 24px}
        .site-header{border-bottom:2px solid var(--ink)}.nav{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:18px 24px}.brand{display:flex;align-items:center;gap:12px;font-family:var(--display);font-size:21px;font-weight:800}.brand img{width:30px;height:30px;object-fit:contain}.brand small{display:block;color:var(--soft);font:400 9px var(--body);letter-spacing:.08em;line-height:1}.nav-links{display:flex;gap:24px;color:var(--soft);font-size:14px;font-weight:bold}.nav-cta,.btn{background:var(--clay);color:#fff;padding:11px 17px;border-radius:3px;font-weight:bold}.page{flex:1;padding:60px 0 80px}.back{color:var(--clay);font-weight:bold;font-size:14px}.eyebrow{color:var(--clay);font:700 12px var(--body);letter-spacing:.12em;text-transform:uppercase;margin:24px 0 12px}.layout{display:grid;grid-template-columns:1.15fr .85fr;gap:48px;align-items:start}.hero-image,.placeholder{width:100%;aspect-ratio:4/3;object-fit:cover;background:linear-gradient(135deg,#b8541f,#3b4a54);border-radius:5px}.details{background:#fff;border:1px solid var(--line);padding:26px;border-radius:5px}.details h1{font-family:var(--display);font-size:clamp(2rem,4vw,3.2rem);line-height:1.05;margin:0 0 20px}.details p{color:var(--soft)}.facts{border-top:1px solid var(--line);margin-top:24px}.fact{display:flex;justify-content:space-between;gap:18px;padding:14px 0;border-bottom:1px solid var(--line)}.fact strong{font-size:14px}.fact span{text-align:right;color:var(--soft)}.site-footer{background:var(--ink);color:#c9c4bb;padding:56px 0 24px}.footer-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1fr;gap:32px;padding-bottom:38px}.footer-grid h4{color:var(--bg);font-size:13px;text-transform:uppercase;letter-spacing:.08em;margin:0 0 16px}.footer-grid ul{list-style:none;margin:0;padding:0}.footer-grid li{margin-bottom:10px}.footer-grid a:hover{color:#e7c6ac}.footer-brand p{max-width:30ch;color:#c9c4bb;font-size:14px}.footer-bottom{display:flex;justify-content:space-between;gap:20px;border-top:1px solid rgba(255,255,255,.16);padding-top:20px;font-size:12px}.contact-list li{display:flex;gap:9px;align-items:center}.contact-list .icon-inline{width:15px;height:15px;color:#e7c6ac}@media(max-width:860px){.footer-grid{grid-template-columns:1fr 1fr}}@media(max-width:760px){.nav-links{display:none}.nav{padding:15px 16px}.layout{grid-template-columns:1fr;gap:24px}.page{padding:36px 0 54px}.footer-grid{grid-template-columns:1fr 1fr;gap:24px}.footer-bottom{align-items:flex-start;flex-direction:column;gap:8px}}@media(max-width:480px){.footer-grid{grid-template-columns:1fr}}
        /* Match the shared public interior-page layout */
        .container{max-width:1200px;margin:0 auto;padding:0 24px}.site-header{position:relative}.site-header .nav{max-width:1200px;margin:0 auto}.site-header .nav-cta{display:flex;align-items:center;gap:14px}.site-header .nav-cta .btn{background:var(--clay);color:#fff;padding:14px 22px;border:2px solid transparent;border-radius:2px}
        .site-header .nav-toggle{display:none;border:0;background:transparent;padding:8px}.site-header .nav-toggle span,.site-header .nav-toggle span:before,.site-header .nav-toggle span:after{content:'';display:block;width:20px;height:2px;background:var(--ink);position:relative}.site-header .nav-toggle span:before{position:absolute;top:-6px}.site-header .nav-toggle span:after{position:absolute;top:6px}
        .page{flex:1;padding:0 0 80px}.page-header{background:var(--ink);color:var(--bg);padding:64px 0 48px}.page-header h1{margin:0;color:var(--bg);font-family:var(--display);font-size:clamp(2rem,4vw,2.8rem);line-height:1.05}.breadcrumb{font:400 .78rem var(--body);color:#e7c6ac;margin-bottom:16px;text-transform:uppercase;letter-spacing:.08em}.section-tight{padding:56px 0}.two-col{display:grid;grid-template-columns:1fr 1fr;gap:56px;align-items:center}.back{display:inline-block;margin-bottom:28px}.details{background:transparent;border:0;padding:8px 0}.details h2{font-family:var(--display);font-size:1.1rem;margin:0 0 16px}.details .eyebrow{margin:0 0 16px}.detail-cta{margin-top:28px!important}
        .sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
        .site-header{position:sticky;top:0;z-index:50;background:var(--bg);border-bottom:2px solid var(--ink)}.site-header .brand{gap:10px;font-size:1.3rem;letter-spacing:-.02em}.site-header .brand img{width:30px;height:30px}.site-header .nav-links{gap:32px}.site-header .nav-cta{gap:18px}.site-header .nav-cta .btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;width:auto;height:52px;box-sizing:border-box;padding:14px 28px!important;border:2px solid transparent;border-radius:2px;font-family:var(--body);font-size:.95rem;font-weight:700;line-height:1.6}.site-footer .brand{gap:10px;font-size:1.3rem}.site-footer .brand img{width:22px;height:22px}
        @media(max-width:860px){.two-col{grid-template-columns:1fr;gap:32px}}@media(max-width:760px){.site-header .nav-links{display:none}.site-header .nav-links.open{display:flex;position:absolute;top:100%;left:0;right:0;flex-direction:column;gap:0;background:var(--bg);padding:8px 24px 20px;border-bottom:2px solid var(--ink);z-index:10}.site-header .nav-links.open a{padding:12px 0;border-bottom:1px solid var(--line)}.site-header .nav-toggle{display:block}.section-tight{padding:40px 0}}
    </style>
</head>
<body class="work-details-page">
@include('site.partials.header')
<style>
  .work-details-page .site-header .nav-cta .btn{min-height:38px!important;padding:7px 14px!important;font-size:.82rem!important}
</style>
<main id="main" class="page"><header class="page-header"><div class="container"><div class="breadcrumb"><a href="/our-work">Our Work</a> / {{ $work->title }}</div><h1>{{ $work->title }}</h1></div></header><section class="section-tight"><div class="container"><a class="back" href="/our-work">← Back to Our Work</a><div class="two-col"><div>@if($work->image_path)<img class="hero-image" fetchpriority="high" src="{{ $workImage }}" alt="{{ $work->title }}">@else<div class="placeholder" aria-hidden="true"></div>@endif</div><article class="details"><div class="eyebrow">{{ $work->category ?: 'Brisbane tiling project' }}</div><h2>Project overview</h2><p>{{ $workDescription }}</p><div class="facts"><div class="fact"><strong>When</strong><span>{{ $work->completed_at?->format('j F Y') ?: 'Date not provided' }}</span></div><div class="fact"><strong>Where</strong><span>{{ $work->location ?: 'Brisbane, Queensland' }}</span></div><div class="fact"><strong>Work area</strong><span>{{ $work->area_m2 ? number_format((float) $work->area_m2, 2).' m²' : 'Area not provided' }}</span></div></div><p class="detail-cta"><a class="btn" href="/quote">Get a quote for a similar Brisbane job</a></p></article></div></div></section></main>
@include('site.partials.footer')
<script>
const workNavToggle = document.querySelector('.nav-toggle');
const workNavLinks = document.querySelector('.nav-links');
if (workNavToggle && workNavLinks) workNavToggle.addEventListener('click', () => {
    const open = workNavLinks.classList.toggle('open');
    workNavToggle.setAttribute('aria-expanded', String(open));
});
</script>
</body>
</html>
